name: Clean dependencies
author: PrestaShop
tags:
  - 'v*.*.'
description: 'An easy GA to clean your dependencies before generate artifact'
branding:
  icon: 'check'
  color: 'blue'
inputs:
  path:
    description: 'Additional files & folders to remove'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}