name: Clean dependencies
author: PrestaShop
description: "An easy GA to clean your dependencies before generate artifact"
branding:
  icon: "check"
  color: "blue"
inputs:
  paths:
    description: "Additional files & folders to remove"
    required: false
  working-directory:
    description: "Working directory for cleaning"
    required: false
    default: "./"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.working-directory }}
    - ${{ inputs.paths }}
